:concurrency: 5
:queues:
  - default
  - mailers

:scheduler:
  :schedule:
    check_location_alerts:
      every: <%= ENV.fetch('ALERTS_CHECK_INTERVAL', '5m') %>
      class: CheckLocationAlertsJob
      queue: default
      description: "Check for new location alert data"

production:
  :concurrency: 10

development:
  :concurrency: 2

staging:
  :concurrency: 5
